# Generated by Django 3.1.7 on 2021-05-02 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=50)),
                ('coach', models.CharField(max_length=20)),
                ('group', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=30)),
                ('goal', models.IntegerField(default=0)),
                ('assist', models.IntegerField(default=0)),
                ('y_card', models.IntegerField(default=0)),
                ('r_card', models.IntegerField(default=0)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='splatform.team')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_no', models.IntegerField(default=0)),
                ('h_score', models.IntegerField(default=0)),
                ('a_score', models.IntegerField(default=0)),
                ('match_time', models.DateTimeField()),
                ('match_loc', models.CharField(max_length=20)),
                ('a_team_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='a_team', to='splatform.team')),
                ('h_team_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='h_team', to='splatform.team')),
            ],
        ),
    ]
