# Generated by Django 3.2 on 2021-05-05 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=50, verbose_name='队伍名')),
                ('coach', models.CharField(max_length=20, verbose_name='主教练')),
                ('group', models.CharField(max_length=100, verbose_name='小组')),
            ],
            options={
                'verbose_name_plural': '队伍表',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=30, verbose_name='运动员')),
                ('goal', models.IntegerField(default=0, verbose_name='进球')),
                ('assist', models.IntegerField(default=0, verbose_name='助攻')),
                ('y_card', models.IntegerField(default=0, verbose_name='黄牌')),
                ('r_card', models.IntegerField(default=0, verbose_name='红牌')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='splatform.team', verbose_name='队伍')),
            ],
            options={
                'verbose_name_plural': '队员表',
                'ordering': ['-goal'],
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_no', models.IntegerField(default=0, verbose_name='比赛编号')),
                ('h_score', models.IntegerField(default=0, verbose_name='主队进球')),
                ('a_score', models.IntegerField(default=0, verbose_name='客队进球')),
                ('match_time', models.DateTimeField(verbose_name='比赛时间')),
                ('match_loc', models.CharField(max_length=50, verbose_name='比赛地点')),
                ('a_team_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='a_team', to='splatform.team', verbose_name='客队')),
                ('h_team_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='h_team', to='splatform.team', verbose_name='主队')),
            ],
            options={
                'verbose_name_plural': '比赛表',
            },
        ),
    ]
