# Generated by Django 3.1.7 on 2021-05-03 04:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('splatform', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='a_score',
            field=models.IntegerField(default=0, verbose_name='客队进球'),
        ),
        migrations.AlterField(
            model_name='match',
            name='a_team_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='a_team', to='splatform.team', verbose_name='客队'),
        ),
        migrations.AlterField(
            model_name='match',
            name='h_score',
            field=models.IntegerField(default=0, verbose_name='主队进球'),
        ),
        migrations.AlterField(
            model_name='match',
            name='h_team_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='h_team', to='splatform.team', verbose_name='主队'),
        ),
        migrations.AlterField(
            model_name='match',
            name='match_loc',
            field=models.CharField(max_length=50, verbose_name='比赛地点'),
        ),
        migrations.AlterField(
            model_name='match',
            name='match_no',
            field=models.IntegerField(default=0, verbose_name='比赛编号'),
        ),
        migrations.AlterField(
            model_name='match',
            name='match_time',
            field=models.DateTimeField(verbose_name='比赛时间'),
        ),
        migrations.AlterField(
            model_name='player',
            name='assist',
            field=models.IntegerField(default=0, verbose_name='助攻'),
        ),
        migrations.AlterField(
            model_name='player',
            name='goal',
            field=models.IntegerField(default=0, verbose_name='进球'),
        ),
        migrations.AlterField(
            model_name='player',
            name='player_name',
            field=models.CharField(max_length=30, verbose_name='运动员'),
        ),
        migrations.AlterField(
            model_name='player',
            name='r_card',
            field=models.IntegerField(default=0, verbose_name='红牌'),
        ),
        migrations.AlterField(
            model_name='player',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='splatform.team', verbose_name='队伍'),
        ),
        migrations.AlterField(
            model_name='player',
            name='y_card',
            field=models.IntegerField(default=0, verbose_name='黄牌'),
        ),
        migrations.AlterField(
            model_name='team',
            name='coach',
            field=models.CharField(max_length=20, verbose_name='主教练'),
        ),
        migrations.AlterField(
            model_name='team',
            name='group',
            field=models.CharField(max_length=100, verbose_name='小组'),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_name',
            field=models.CharField(max_length=50, verbose_name='队伍名'),
        ),
    ]
